### ISSUE TITLE
Panic segmentation fault - probably mutex is not initialized 

### ISSUE THREAD

**Issue by axlev** [gopcua/opcua#365]
Hello,
I have used subscribe example from here 
https://github.com/gopcua/opcua/blob/master/examples/subscribe/subscribe.go

to monitor a value in OPCUA server, modified context with timeout to context with cancel tough . After 3.5 hours OPC server stopped to respond and for some reason it caused client to panic as following:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2c pc=0x5866c3]

goroutine 23 [running]:
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:74
github.com/gopcua/opcua/uasc.(*SecureChannel).sendAsyncWithTimeout(0x0, 0x650160, 0xc00011a1e0, 0xc00008f080, 0x1, 0xdf8475800, 0x0, 0x0, 0x0, 0x0)
        /home/alex/go/pkg/mod/github.com/gopcua/opcua@v0.1.11/uasc/secure_channel.go:194 +0x63
github.com/gopcua/opcua/uasc.(*SecureChannel).SendRequestWithTimeout(0x0, 0x650160, 0xc00011a1e0, 0xc00008f080, 0xdf8475800, 0xc0004adec8, 0x0, 0x0)
        /home/alex/go/pkg/mod/github.com/gopcua/opcua@v0.1.11/uasc/secure_channel.go:161 +0x92
github.com/gopcua/opcua.(*Client).sendWithTimeout(0xc00016c100, 0x650160, 0xc00011a1e0, 0xdf8475800, 0xc0004adec8, 0xc0004aded8, 0x40798a)
        /home/alex/go/pkg/mod/github.com/gopcua/opcua@v0.1.11/client.go:486 +0xaf
github.com/gopcua/opcua.(*Subscription).publish(0xc0001242a0, 0xc0001221b0, 0x1, 0x1, 0x0, 0x64ef20, 0xc00015a2d0)
        /home/alex/go/pkg/mod/github.com/gopcua/opcua@v0.1.11/subscription.go:124 +0x118
github.com/gopcua/opcua.(*Subscription).Run(0xc0001242a0, 0x651840, 0xc000022980)
        /home/alex/go/pkg/mod/github.com/gopcua/opcua@v0.1.11/subscription.go:155 +0xb0
created by main.main
        /home/alex/workspaces/opcua/main.go:109 +0xae8
```

**Can you please take a look if I did anything wrong or is there a bug ?**
 
Thanks & Regards,
Alex

**Comment by magiconair** [comment]
The subscription logic is going to change for 0.2. So lets have a look whether this is still relevant.
